### ISSUE TITLE
View application details for an existing identifier

### ISSUE THREAD

**Issue by marlabrizel** [applegrain/traffic-spy#11]
As a registered user
After sending a payload
When I access http://yourapplication:port/sources/IDENTIFIER with an identifier that exists
I will see a page that displays:
- Most requested URLS to least requested URLS (url)
- Web browser breakdown across all requests (userAgent)
- OS breakdown across all requests (userAgent)
- Screen Resolution across all requests (resolutionWidth x resolutionHeight)
- Longest, average response time per URL to shortest, average response time per URL
- Hyperlinks of each url to view url specific data
- Hyperlink to view aggregate event data

**Comment by applegrain** [comment]
Add model tests for above functionality
